### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by ReynerHL** [bhoriuchi/vue-deepset#10]
**vue**: 2.5.13
**vuex**: 3.0.1
**vue-deepset version**: 0.6.0
**Code Example**: https://codesandbox.io/s/6l0r4wznzw (sorry for the mess, I'm in a hurry here)

After upgrade to the new 0.6.0 version, I've faced with this new error:

TypeError: _this.$vuexSet is not a function
Uncaught (in promise) TypeError: Cannot read property 'status' of undefined

I've forked the example code to another one using the previous version here:

https://codesandbox.io/s/nwk241p6nl

As you can see, version 0.5.4 handles (resolves) well the **"this.$vuexSet"** call in the mounted hook, but the new version 0.6.0 can't.

Thanks for your time.

**Comment by bhoriuchi** [comment]
yep, looks like i forgot to add it to the install method. patch to be released shortly

**Comment by bhoriuchi** [comment]
this has been added back in `v0.6.1`

**Comment by ReynerHL** [comment]
I can confirm this issue is no longer present. Thanks for the quick response and fix.

**Comment by xuwentao93** [comment]
wow, such a nice anwser.

**Comment by xuwentao93** [comment]
wow, such a nice answer.
