### ISSUE TITLE
Cannot find path in Vuex modules

### ISSUE THREAD

**Issue by ReynerHL** [bhoriuchi/vue-deepset#11]
We have used Vuex modules with previous vue-deepset versions, but after the latest update, we are facing with this new error:
"Error: [vue-deepset]: cannot find path "WarehouseModule.adjustmentForm" in Vuex store"

I've created an example that shows the issue:
https://codesandbox.io/s/kk1x169735

If we use the same example but with vue-deepset@5.4 it works.

Thanks for your time.

**Comment by bhoriuchi** [comment]
Good catch! there was a bug in the has method where it was always referencing the top level object instead of descending the path. This has been fixed and published in `v0.6.2`
