### ISSUE TITLE
Complex nested path not working with 0.6.2

### ISSUE THREAD

**Issue by ReynerHL** [bhoriuchi/vue-deepset#12]
In this code example, we are using vue-deepset 0.5.4 with vuex modules and v-model bindings to nested loops in templates. But if we upgrade to the 0.6.2 version, it does not work anymore.

https://codesandbox.io/s/vqmn4olqkl

Yes, we know we are always putting this package to the limits, but this is because we love it :)

**Comment by bhoriuchi** [comment]
seems to be an issue with topath as when using ``libraryModel[`books.${bookIndex}.fans.${fanIndex}.name`]`` it works

**Comment by bhoriuchi** [comment]
I rolled back the `toPath` and `vueSet` methods to the older code and it resolved the issue. `v0.6.3` published to npm. thanks for all your testing!

**Comment by ReynerHL** [comment]
Thanks to you, for always being giving a great support to the issues we found.

Just for be clear, this kind of notation:
```html
libraryModel[`books.${bookIndex}.fans.${fanIndex}.name`]
```

Will be fine for indexing arrays and access objects properties values as well?

**Comment by bhoriuchi** [comment]
Yeah it should be ok. I might export the supporting methods like toPath and get so devs can test them out

**Comment by ReynerHL** [comment]
Thanks, we can close this issue now.
