### ISSUE TITLE
VUEX_DEEP_SET mutation called twice for every model update

### ISSUE THREAD

**Issue by ReynerHL** [bhoriuchi/vue-deepset#2]
Inspecting throught VueDevTool, we can see that the VUEX_DEEP_SET mutation is called twice every time a model is updated. Perhaps this is not critical, but might deserve a look.

**Comment by bhoriuchi** [comment]
This has been resolved in https://github.com/bhoriuchi/vue-deepset/releases/tag/v0.5.0

see release notes for details
