### ISSUE TITLE
VueDeepSet.extendMutation with modules

### ISSUE THREAD

**Issue by pmooredesigner** [bhoriuchi/vue-deepset#3]
Thank you for this package.  It has worked well for me on my current Vue project, considering I'm trying to find the most efficient and the least tedious way to 2-way bind large Vuex objects to components.  

I ran into some issues recently, and I wanted to confirm if part of what I'm doing is correct before I explain further.  If I'm using namespaced modules for Vuex, can I still use the code I'm showing below, with the mutation at the root? I did try wrapping each module's mutations with VueDeepSet.extendMutation() , but it didn't seem to fix my particular issue.

```
const store = new Vuex.Store({
    plugins: [createPersistedState()],
    modules,
    mutations: VueDeepSet.extendMutation()
});
```

Thanks,
Paul

**Comment by ReynerHL** [comment]
We use this package with Vuex modules, and only register the VUEX_DEEP_SET mutation once in the root store.

Perhaps a fiddle can help us here, please, feel free to modify as you wish and share your issue:

https://jsfiddle.net/reynerhl/1L4ywy2t/2/

**Comment by bhoriuchi** [comment]
You should be able to use modules with the example store you shared, you just need to set the path for the module in separate $deepModel calls

**Comment by pmooredesigner** [comment]
Thanks.  I think I do have the binding set up correctly, and that part works.  My issues probably have nothing to do with vue-deepset, so I won't bother you about the specifics.

I do just want to ask one further question about the package, and then I'll be done.  I'm using a computed property as shown below.  Is it preferable or necessary to always change this computed property directly, or are normal Vuex mutations just as fine to use?

```
computed: {
    contact: function() {
        return this.$deepModel('contact.record'); // referring to a Vuex module named 'contact'
    }
}
```

For instance, can I use something like this without interfering with vue-deepset?

```
mutations: {
    updateRecord: function(state, contact) {
        state.record = _.assign({}, state.record, contact);
    }
}
```

**Comment by pmooredesigner** [comment]
The app I'm working on is starting to get complex (for me at least). I would love to be able to confidently implement this package, because I haven't found another solution for what I'm trying to do.  Would you be available for an hour of paid consulting? If not, no problem.  If so, please email me at pmooredesigner@gmail.com .

Thanks,
Paul
