### ISSUE TITLE
When opening vue dev tools,  get some error

### ISSUE THREAD

**Issue by congpeijun** [bhoriuchi/vue-deepset#4]
https://jsfiddle.net/congpeijun/mz5s5t1z/18/

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>Document</title>
  <script src="https://unpkg.com/vue@2.4.2/dist/vue.js"></script>
  <script src="https://unpkg.com/vue-deepset@0.5.0/vue-deepset.js"></script>
</head>

<body>
  <div id="app">
    <input type="text" v-model="order.a[0]">
    <pre v-text="order"></pre>
  </div>
  <script type="text/javascript">
  Vue.use(VueDeepSet);
  var app = new Vue({
    el: '#app',
    data() {
      return {
        orderShadow: { a: [] }
      }
    },
    computed: {
      order() {
        return this.$deepModel(this.orderShadow);
      }
    }
  });
  </script>
</body>

</html>

```

**Comment by congpeijun** [comment]
It appears when click the component node

**Comment by bhoriuchi** [comment]
You should be using v-model="order['a[0]']"

The whole purpose of this library is because you cannot specify deep paths in v-model which is a vue limitation. That is why vue-deepest has you put a path string as the key.

**Comment by congpeijun** [comment]
@bhoriuchi Thanks!  But it still has some errors.
First open Vue Devtools
Click the root Component Node. the errors appear.
Then file something into the input, errors going on. 
![image](https://user-images.githubusercontent.com/881552/29464531-ba821b36-8468-11e7-8f9c-b79b0cdcd8d1.png)

**Comment by bhoriuchi** [comment]
i am not seeing any issue with https://jsfiddle.net/vbranden/mz5s5t1z/20/ in Vue DevTools or chrome devtools console.

**Comment by bhoriuchi** [comment]
i see the issue now, chrome wasnt loading my devtools correctly. i will look into this.

**Comment by ReynerHL** [comment]
@bhoriuchi How did you fix the problem with VueDev tool in Chrome ? I'm still no able to see the VueTab from any fiddle and this one, is working well for me.

**Comment by bhoriuchi** [comment]
Please try version `0.5.1`. It seems vue devtools is attempting to look up symbols and the get/has helper methods are interpreting the symbol property as a string and trying to look up the path. this has been handled in the latest release. let me know if your issue is resolved.

**Comment by congpeijun** [comment]
👍 It works now! Thanks very much!
I like this project, I reduct a lot of typing.
Good Job!

**Comment by bhoriuchi** [comment]
Great!

**Comment by bhoriuchi** [comment]
You need to open the result iframe in a new window. There is a thread on it
in vue forum
