### ISSUE TITLE
Add computed field with deepest path

### ISSUE THREAD

**Issue by kenti-lan** [bhoriuchi/vue-deepset#5]
What if i want to add a computed field like this:
`
computed: {
        "foo.bar":{
          get:function () {
           console.log("get foo.bar ");
          },set:function () {

            }
        }
    }
`.
This means I want the foo.bar to be a computed property.When i use this in vue,{{foo.bar}},vue will 
call the getter function of foo.bar property.

**Comment by bhoriuchi** [comment]
I'm not sure how your question applies to this project. Can you please clarify?

**Comment by bhoriuchi** [comment]
this issue has no reference to the project. I'm going to assume this was meant to be a general vuejs question which should be asked on the vuejs project or stackoverflow
