### ISSUE TITLE
How to use $deepModel for modules in vuex

### ISSUE THREAD

**Issue by minhtruong92** [bhoriuchi/vue-deepset#6]
I'm using vuex and I have some modules but I don't know how to use $deepModel with module ? I try to use this.$deepModel("moduleName.stateProperty") but seem it's not work correctly

**Comment by bhoriuchi** [comment]
Please add code to reproduce, preferably in a jsfiddle. Thanks!

**Comment by ReynerHL** [comment]
@minhtruong92 Here you can see an example using modules. Perhaps this is not the best way, but it worked for me.
https://jsfiddle.net/reynerhl/1L4ywy2t/

**Comment by minhtruong92** [comment]
@bhoriuchi bh
@ReynerHL Rey
This is my case : https://jsfiddle.net/1L4ywy2t/3/ 
(when you input value to textbox and tab out, you will see error message at console : Error: [vuex] Do not mutate vuex store state outside mutation handlers.)

I'm using vuex with many fields use v-model ( almost my model must use state of vuex ) and I want to use 2 ways binding the same use v-model of vuejs but I got some issues can't use tricky like this link https://vuex.vuejs.org/en/forms.html 

Why ? 
1. I use component replace "native input" HTML, if use :value="model" and @input = "callToAction" follow vuex document, we will ignore some business logic excuted in component (eg: if user input characters to component only accept number, our model won't match with component)

2. I try to use get() , set() in computed, but we stuck with nested object in state. Luckily, I found vue-deepset support me to use v-model.

**Comment by ReynerHL** [comment]
@minhtruong92 Sorry, can you help me to understand what actually you are trying to reach ? I've updated your example with this:

https://jsfiddle.net/reynerhl/rn5g1d5g/1/

I suppose you can't use a module as a new Vuex instance. Instead, create a "config module" as an object and let Vuex to register it in its own logic.

You can open your devtools and see there is not error now. Please, let me know if this helped you.

**Comment by bhoriuchi** [comment]
this appears to be a valid bug from looking at your fiddle. I will look at this when I get a chance.

**Comment by bhoriuchi** [comment]
@minhtruong92 I actually got everything to work with out changing any of the vue-deepset code. I modified your fiddle, see updated https://jsfiddle.net/1L4ywy2t/4/

I removed product from being in its own store which was causing the majority of the issue. I'm not sure why this was done but it seems unnecessary and problematic. The second thing I modified was removing the extendMutation from the module since the root mutation is capable of modifying nested stores already it is not necessary to add another to the module. Let me know if implementing these changes in your code solves your issue.

**Comment by minhtruong92** [comment]
@bhoriuchi Thank you for your good support, you make my day. It work like a charm!

**Comment by minhtruong92** [comment]
Hi @bhoriuchi @ReynerHL , I test with nested object state, it doesn't seem to work. You can see error message at console

Update here :
https://jsfiddle.net/1L4ywy2t/5/

**Comment by ReynerHL** [comment]
@minhtruong92 Try using another notation when you bind to your model, like this:

```html
<input type="text" v-model="product['name.innerName']">
```

https://jsfiddle.net/reynerhl/1Ltk2fhy/

Let me know if this helps to you.

**Comment by minhtruong92** [comment]
@ReynerHL Thank you so much, it help me more. 👍

**Comment by bhoriuchi** [comment]
@minhtruong92 can this issue be closed?

**Comment by minhtruong92** [comment]
@bhoriuchi Yes, thank you so much, it's a great support!
